Server:
    RunMode: debug
    HttpPort: 8000
    ReadTimeout: 60
    WriteTimeout: 60
App:
    DefaultContextTimeout: 60
    DefaultPageSize: 10
    MaxPageSize: 100
    LogSavePath: storage/logs
    LogFileName: app
    LogFileExt: .log
Database:
    DBType: mysql
    Username: root
    Password: abc123
    Host: 127.0.0.1
    Port: 3306
    DBName: demo_service
    TablePrefix: demo_
    Charset: utf8mb4
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30
JWT:
    Secret: demo_golang
    Issuer: demo
    Expire: 7200
Email:
    Host: smtp.qq.com
    Port: 465
    UserName: xxx
    Password: xxx
    IsSSL: true
    From: xxx
    To:
        - xxx
